In [1]:
#Jia Yi/Susan Wang

In [2]:
import pandas as pd
import numpy as np

In [3]:
data1 = pd.read_json('data/genres.json.gz', orient='record', lines=True, encoding='utf-8')

In [4]:
data1

                                            genre_label wikidata_id
0                                               novella   Q43334491
1                                             cityscape   Q42304051
2                                      drama with music   Q39894018
3                                             lunar art   Q47909472
4                                    Tsukuri monogatari   Q42922249
5                                traditional fairy tale   Q42402646
6                                    fantasy video game   Q42409239
7                                       propaganda song   Q42681239
8                                           miniaturist   Q47494964
9                                           Breton rock   Q47005557
10                                     apocalyptic film   Q47009776
11                                         Adhyan Dhara   Q47528634
12                                           trap music   Q47781397
13                                                 card   Q42965339
14                                       intuitive folk   Q51560345
15                                                drama   Q39892385
16                                            Volkslied   Q40039114
17    Social dramatics: social skills development fo...   Q41462152
18                        Digital collectible card game   Q48997688
19                              traditional Welsh music   Q48297861
20                                                nanas   Q48696022
21                          Theatre for Young Audiences   Q48996995
22                                    crime radio drama   Q47214765
23                                          Banish Shah   Q47308210
24                                 confessional fiction   Q47472667
25                                              Intriga   Q48834789
26                                   Arthurian painting   Q53017426
27                                             computer         Q68
28                                             Internet         Q75
29                                                space        Q107
...                                                 ...         ...
5529                                             Novela   Q11325830
5530                                  political thought   Q11499141
5531                                Biblical commentary   Q11611056
5532                          Prefecture songs of Japan   Q11643859
5533                                      Militia novel   Q11825891
5534                                  young adult novel   Q11825892
5535                                               list   Q12139612
5536                               Bulgarian folk music   Q12274232
5537                                   poetry anthology   Q12308638
5538                                           Tropical   Q22909492
5539                                 treasure hunt film   Q22981906
5540                                        Superheroes   Q23746792
5541                              science fiction novel   Q12132683
5542                                             Balada   Q12473659
5543                                             Balada   Q12683301
5544                                       neosymbolism   Q12772445
5545                                             powest   Q12799318
5546                                           producer   Q13235160
5547                                            Mystery   Q13377795
5548                                   street furniture   Q13397636
5549                           philosophical literature   Q13408937
5550                                       Funk carioca   Q13436880
5551                                Texas country music   Q14493900
5552                                        object file   Q14902318
5553                                  apocalyptic novel   Q26225484
5554                                    cyberpunk novel   Q26228231
5555                                            Eastern   Q26268098
5556                                       hunting deck   Q26965555
5557                                             Lirico   Q22349373
5558                                          engraving   Q22669429

[5559 rows x 2 columns]

In [5]:
data2 = pd.read_json('data/omdb-data.json.gz', orient='record', lines=True, encoding='utf-8')

In [6]:
data2

,imdb_id,omdb_awards,omdb_genres,omdb_plot
0,tt0060814,Nominated for 2 Oscars. Another 2 nominations.,"[Drama, History, War]","In this sprawling, star-laden film, we see the..."
1,tt2379713,Won 1 Oscar. Another 7 wins & 32 nominations.,"[Action, Adventure, Thriller]",A cryptic message from the past sends James Bo...
2,tt0230575,N/A,"[Comedy, Horror]","The makers of this parody of ""Night of the Liv..."
3,tt0065988,Nominated for 1 Oscar. Another 5 wins & 8 nomi...,"[Adventure, Comedy, Drama]",Jack Crabb is 121 years old as the film begins...
4,tt1995390,2 nominations.,"[Crime, Drama, Thriller]","When Perry and his girlfriend, Gail, cross pat..."
5,tt0066921,Nominated for 4 Oscars. Another 9 wins & 19 no...,"[Crime, Drama, Sci-Fi]","Protagonist Alex DeLarge is an ""ultraviolent"" ..."
6,tt1298650,2 wins & 31 nominations.,"[Action, Adventure, Fantasy]",Captain Jack Sparrow (Depp) crosses paths with...
7,tt0069947,Nominated for 1 Oscar. Another 1 win & 10 nomi...,"[Crime, Drama, Thriller]",It is the early 60s in France. The remaining s...
8,tt0116629,Won 1 Oscar. Another 34 wins & 34 nominations.,"[Action, Adventure, Sci-Fi]","On July 2nd, communications systems worldwide ..."
9,tt0057012,Nominated for 4 Oscars. Another 13 wins & 7 no...,"[Comedy, War]",Paranoid Brigadier General Jack D. Ripper of B...
10,tt1568346,Won 1 Oscar. Another 27 wins & 90 nominations.,"[Crime, Drama, Mystery]",This English-language adaptation of the Swedis...
11,tt1504320,Won 4 Oscars. Another 102 wins & 194 nominations.,"[Biography, Comedy, Drama]",England's Prince Albert must ascend the throne...
12,tt0120737,Won 4 Oscars. Another 113 wins & 123 nominations.,"[Adventure, Drama, Fantasy]",An ancient Ring thought lost for centuries has...
13,tt0800080,1 win & 8 nominations.,"[Action, Adventure, Sci-Fi]",Depicting the events after the Gamma Bomb. 'Th...
14,tt1226229,14 nominations.,"[Adventure, Comedy, Music]",English rock star Aldous Snow relapses into dr...
15,tt2395427,7 wins & 45 nominations.,"[Action, Adventure, Sci-Fi]",Tony Stark creates the Ultron Program to prote...
16,tt0368891,1 win & 9 nominations.,"[Action, Adventure, Family]",Benjamin Franklin Gates descends from a family...
17,tt0057076,Nominated for 1 Golden Globe. Another 3 wins &...,"[Action, Adventure, Thriller]",James Bond 007 is on the search for a Russian ...
18,tt0371746,Nominated for 2 Oscars. Another 20 wins & 65 n...,"[Action, Adventure, Sci-Fi]","Tony Stark. Genius, billionaire, playboy, phil..."
19,tt2381249,6 wins & 23 nominations.,"[Action, Adventure, Thriller]",CIA chief Hunley (Baldwin) convinces a Senate ...
20,tt0434409,7 wins & 27 nominations.,"[Action, Drama, Sci-Fi]",Tells the story of Evey Hammond and her unlike...
21,tt0816711,3 wins & 24 nominations.,"[Action, Adventure, Horror]",Life for former United Nations investigator Ge...
22,tt0241527,Nominated for 3 Oscars. Another 17 wins & 62 n...,"[Adventure, Family, Fantasy]","This is the tale of Harry Potter, an ordinary ..."
23,tt0480249,9 wins & 22 nominations.,"[Drama, Horror, Sci-Fi]",Robert Neville is a scientist who was unable t...
24,tt0115956,9 wins & 7 nominations.,"[Action, Drama, Mystery]","The pilot of a rescue copter, Captain Karen Wa..."
25,tt1194173,1 win & 11 nominations.,"[Action, Adventure, Mystery]",The events in this movie take place around the...
26,tt2872732,1 win & 11 nominations.,"[Action, Sci-Fi, Thriller]",It was supposed to be a simple job. All Lucy h...
27,tt0383574,Won 1 Oscar. Another 42 wins & 53 nominations.,"[Action, Adventure, Fantasy]",Once again we're plunged into the world of swo...
28,tt0102926,Won 5 Oscars. Another 54 wins & 44 nominations.,"[Crime, Drama, Thriller]",FBI trainee Clarice Starling works hard to adv...
29,tt0064757,Nominated for 1 Golden Globe. Another 1 win & ...,"[Action, Adventure, Thriller]",George Lazenby steps into the role of James Bo...
...,...,...,...,...
9646,tt0369738,N/A,"[Action, Drama]",A retired Diplomat and an NYPD Detective seeki...
9647,tt3469798,2 nominations.,"[Drama, Romance, Sci-Fi]",Helena is a young girl who spent all her life ...
9648,tt0432348,4 wins & 8 nominations.,"[Horror, Mystery]",When detective Eric Matthews is called to a cr...
9649,tt0220570,2 wins.,[Drama],The story is about a stripper's relationships ...
9650,tt0029855,Nominated for 4 Oscars. Another 1 win & 1 nomi...,"[Drama, Mystery, Romance]","Pepe Le Moko, a thief who escaped from France ..."
9651,tt0299422,1 win.,[Comedy],A dark comedy about three salesmen from Detroi...
9652,tt0387564,8 wins & 10 nominations.,"[Crime, Horror, Mystery]",Waking up in a undisclosed location in a unkno...
9653,tt1821362,N/A,[Comedy],Two black brothers send back to slavery time
9654,tt3276924,N/A,"[Action, Crime, Thriller]",When their attempt to rob a casino owned by th...
9655,tt3805180,N/A,"[Comedy, Crime]",Tim and Dan - fellow losers from a provincial ...
9656,tt0092033,N/A,[Drama],"Sharda, a nurse and single mother, raises her ..."
9657,tt0120514,Nominated for 1 Golden Globe. Another 4 wins &...,"[Biography, Drama, Romance]","The story of Oscar Wilde, genius, poet, playwr..."
9658,tt0078870,1 win & 1 nomination.,"[Adventure, Comedy]",A rediscovered classic from director Ken Loach...
9659,tt1819769,N/A,[Drama],Ray enrolls in art school where he makes new f...
9660,tt0087313,N/A,"[Comedy, Drama]",Estelle is a one-person protest army: she goes...
9661,tt2318405,4 wins & 7 nominations.,"[Action, Adventure, Fantasy]","In WW2, after a tank battle, a wounded Soviet ..."
9662,tt0254617,N/A,"[Comedy, Romance]",A young woman is in Orlando visiting her ailin...
9663,tt0266489,2 nominations.,[Comedy],Alex Rose and Nancy Kendricks are a young coup...
9664,tt0280962,4 wins & 2 nominations.,"[Crime, Horror, Romance]",A terrifying love triangle. An original twist ...
9665,tt0298491,10 wins & 3 nominations.,"[Drama, Fantasy, Thriller]","Nicklas lives a pretty normal teenage life, un..."
9666,tt0978702,N/A,[Drama],"Raghavendra, Vishnu, Chinna, and Vamsi are bro..."
9667,tt0096219,3 wins & 5 nominations.,[Drama],An acerbic radio talk show host based in Dalla...
9668,tt1986994,N/A,"[Fantasy, Horror, Thriller]","""Season of the Equinox, the witch besets her k..."
9669,tt1183487,5 wins.,[Drama],Colin Mc Nally couldn't give a toss about the ...
9670,tt0113101,1 win & 1 nomination.,[Comedy],This movie features the collaborative director...
9671,tt0052365,2 wins & 1 nomination.,"[Action, Adventure]",Einar and Eric are two Viking half-brothers. T...
9672,tt0088099,2 wins & 1 nomination.,"[Comedy, Drama, Romance]",In lieu of love and affections from his multi-...
9673,tt5580036,Nominated for 3 Oscars. Another 31 wins & 109 ...,"[Biography, Comedy, Drama]",Competitive ice skater Tonya Harding rises amo...
9674,tt2244376,16 wins & 34 nominations.,[Drama],Plot: Bwakaw is a drama-comedy about growing o...
9675,tt4986098,N/A,"[Sci-Fi, Thriller]",A military family takes part in a ground-break...

In [7]:
data3 = pd.read_json('data/rotten-tomatoes.json.gz', orient='record', lines=True, encoding='utf-8')

In [8]:
data3

,audience_average,audience_percent,audience_ratings,critic_average,critic_percent,imdb_id,rotten_tomatoes_id
0,3.9,86.0,33125227.0,7.1,79.0,tt0325980,m/pirates_of_the_caribbean_the_curse_of_the_bl...
1,4.1,80.0,2139.0,7.8,88.0,tt4882376,m/first_they_killed_my_father_a_daughter_of_ca...
2,3.6,71.0,11482.0,7.6,86.0,tt0099763,m/henry_portrait_of_a_serial_killer
3,3.6,66.0,187204.0,6.6,66.0,tt1371111,m/cloud_atlas_2012
4,3.9,84.0,26836.0,7.4,80.0,tt1189073,m/the_skin_i_live_in
5,3.7,74.0,1498.0,7.0,88.0,tt1787725,m/if_a_tree_falls_a_story_of_the_earth_liberat...
6,3.6,85.0,92824.0,6.6,73.0,tt0117665,m/1073595-sleepers
7,3.2,50.0,242347.0,4.9,35.0,tt1611224,m/abraham_lincoln_vampire_hunter
8,4.0,87.0,427.0,7.4,100.0,tt3966544,m/lost_soul_the_doomed_journey_of_richard_stan...
9,3.7,74.0,260776.0,7.4,85.0,tt0780521,m/1196003-princess_and_the_frog
10,3.3,51.0,241740.0,4.3,30.0,tt1855325,m/resident_evil_retribution
11,3.2,66.0,46826.0,7.3,85.0,tt0115956,m/courage_under_fire
12,3.4,69.0,23375.0,7.4,90.0,tt0068555,m/everything_you_always_wanted_to_know_about_s...
13,3.5,54.0,199136.0,5.0,32.0,tt1298650,m/pirates_of_the_caribbean_on_stranger_tides
14,3.3,57.0,109.0,NaN,NaN,tt0230575,m/night_of_the_day_of_the_dawn_of_the_son_of_t...
15,3.3,64.0,188527.0,5.5,38.0,tt0328880,m/brother_bear
16,4.3,92.0,279153.0,7.6,89.0,tt1843866,m/captain_america_the_winter_soldier_2014
17,3.6,63.0,304.0,7.1,83.0,tt1931549,m/the_man_nobody_knew_in_search_of_my_father_c...
18,3.2,46.0,480.0,4.9,45.0,tt1979172,m/a_liars_autobiography_the_untrue_story_of_mo...
19,3.4,80.0,140836.0,7.6,84.0,tt0311113,m/master_and_commander_the_far_side_of_the_world
20,4.2,89.0,138111.0,7.4,86.0,tt1659337,m/perks_of_being_a_wallflower
21,3.5,58.0,37565.0,5.7,60.0,tt1698641,m/alexander_and_the_terrible_horrible_no_good_...
22,3.4,74.0,266365.0,6.2,57.0,tt0396171,m/perfume_the_story_of_a_murderer
23,2.8,34.0,7246.0,5.0,55.0,tt1659343,m/universal_soldier_day_of_reckoning
24,3.1,61.0,34104919.0,6.9,76.0,tt0363771,m/chronicles_of_narnia_lion_witch_wardrobe
25,4.0,93.0,435893.0,8.4,89.0,tt0066921,m/clockwork_orange
26,3.4,73.0,70542.0,6.0,74.0,tt0105112,m/patriot_games
27,4.0,91.0,336264.0,8.5,90.0,tt0083658,m/Blade_Runner
28,3.8,89.0,297648.0,9.2,92.0,tt0062622,m/1000085-2001_a_space_odyssey
29,3.3,60.0,4949.0,4.7,22.0,tt0409034,m/marilyn_hotchkiss_ballroom_dancing_and_charm...
...,...,...,...,...,...,...,...
40200,4.6,100.0,20.0,NaN,NaN,tt3037570,m/alt
40201,3.2,56.0,1354.0,6.8,100.0,tt0042644,m/kim
40202,3.3,64.0,290.0,NaN,NaN,tt0116844,m/lea
40203,NaN,NaN,13.0,NaN,NaN,tt0099890,m/jit
40204,NaN,NaN,1.0,NaN,NaN,tt0264210,m/zor
40205,NaN,NaN,2.0,NaN,NaN,tt0340280,m/out
40206,3.2,40.0,185.0,NaN,NaN,tt0088781,m/beer
40207,3.8,79.0,366.0,NaN,NaN,tt0150980,m/hanyo
40208,3.0,52.0,16432.0,4.0,10.0,tt0084809,m/toy
40209,3.0,62.0,5393.0,3.5,10.0,tt0120531,m/woo
40210,3.7,60.0,68.0,NaN,NaN,tt0262196,m/19
40211,3.7,79.0,4304.0,5.8,57.0,tt0250638,m/ptu
40212,NaN,NaN,8.0,NaN,NaN,tt1215486,m/tug
40213,3.9,88.0,1703.0,7.5,92.0,tt0116589,m/hype
40214,3.3,67.0,790.0,5.1,22.0,tt0077532,m/fm
40215,3.6,73.0,66.0,NaN,NaN,tt1452297,m/poll
40216,3.7,61.0,324.0,NaN,NaN,tt0091507,m/melo
40217,3.0,38.0,8538.0,NaN,NaN,tt0385560,m/boo
40218,3.1,64.0,37580.0,5.0,53.0,tt0110638,m/nell
40219,NaN,NaN,52.0,NaN,NaN,tt0105712,m/utz
40220,3.4,63.0,1149.0,6.4,86.0,tt0065916,m/joe
40221,3.4,68.0,2061.0,5.6,50.0,tt0098442,m/tap
40222,3.4,53.0,770.0,NaN,NaN,tt0364146,m/105
40223,2.4,20.0,224.0,NaN,NaN,tt1261041,m/222
40224,4.1,90.0,7841.0,7.7,89.0,tt0388888,m/dig
40225,3.6,69.0,2350.0,NaN,NaN,tt0099429,m/dil
40226,4.3,70.0,118.0,NaN,NaN,tt1053792,m/41
40227,3.8,84.0,309.0,NaN,NaN,tt0088658,m/ak
40228,2.9,53.0,14648.0,6.4,68.0,tt0078721,m/10
40229,NaN,NaN,0.0,NaN,NaN,tt2779840,m/916

In [9]:
data4 = pd.read_json('data/wikidata-movies.json.gz', orient='record', lines=True, encoding='utf-8')

In [10]:
data4

,based_on,cast_member,country_of_origin,director,enwiki_title,filming_location,genre,imdb_id,label,made_profit,main_subject,metacritic_id,original_language,publication_date,rotten_tomatoes_id,series,wikidata_id
0,NaN,"[Q228931, Q235384]",Q145,[Q43079418],If I Were You (2012 Canadian film),NaN,[Q859369],tt1587309,If I Were You,NaN,NaN,NaN,Q1860,2012-01-01,m/if_i_were_you_2012,NaN,Q43079072
1,NaN,NaN,Q30,NaN,Krampus: The Devil Returns,NaN,[Q28026639],tt3527772,Krampus: The Devil Returns,NaN,NaN,NaN,Q1860,2016-10-04,m/krampus_the_devil_returns,NaN,Q43302269
2,NaN,"[Q106303, Q467957, Q3345693, Q3340838, Q316419...",Q142,[Q724208],Le Brio,[Q50742],[Q157443],tt6462462,NaN,NaN,NaN,NaN,Q150,2017-01-01,m/le_brio,NaN,Q43400054
3,NaN,NaN,Q30,[Q4718041],A Christmas Prince,NaN,"[Q860626, Q28026639]",tt7608418,A Christmas Prince,NaN,NaN,NaN,Q1860,2017-11-17,m/a_christmas_prince,NaN,Q43401863
4,Q7162696,NaN,Q252,[Q11036795],Pengabdi Setan (2017 film),NaN,[Q200092],tt7076834,Pengabdi Setan,NaN,NaN,NaN,Q9240,2017-01-01,m/satans_slaves,NaN,Q41850450
5,NaN,NaN,Q258,NaN,A Small Town Called Descent,NaN,[Q959790],tt3726330,A Small Town Called Descent,NaN,NaN,NaN,Q1860,2010-07-24,m/a_small_town_called_descent,NaN,Q42048906
6,NaN,"[Q5126010, Q3390414, Q5676024, Q237021]",Q29,[Q51892574],Orbiter 9,NaN,"[Q24925, Q21010853]",tt3469798,Orbiter 9,0.0,NaN,NaN,NaN,2017-04-07,m/orbiter_9,NaN,Q42577704
7,Q18214949,"[Q202381, Q7367121, Q179576, Q20630818, Q28474...",Q30,[Q18608206],The Kindergarten Teacher (2018 film),NaN,[Q130232],tt6952960,The Kindergarten Teacher,NaN,NaN,NaN,Q1860,2018-01-01,m/the_kindergarten_teacher_2018,NaN,Q47461695
8,NaN,NaN,Q30,[Q22073902],Who the Fuck Is That Guy? The Fabulous Journey...,NaN,[Q93204],tt4958390,Who the Fuck is That Guy? The Fabulous Journey...,NaN,NaN,NaN,Q1860,2017-07-21,m/who_the_fk_is_that_guy_the_fabulous_journey_...,NaN,Q47483224
9,NaN,NaN,Q30,NaN,The Black Dove,NaN,[Q130232],tt1844790,The Black Dove,NaN,NaN,NaN,Q1860,2012-04-19,m/the_black_dove,NaN,Q42048757
10,NaN,"[Q41548, Q15712136, Q1104856]",Q219,[Q768543],Acts of Vengeance (film),NaN,[Q188473],tt6288694,Acts of Vengeance,NaN,NaN,movie/acts-of-vengeance,Q1860,2017-01-01,m/acts_of_vengeance,NaN,Q42289722
11,NaN,NaN,Q408,NaN,OtherLife,NaN,"[Q471839, Q2484376]",tt4693358,OtherLife,NaN,NaN,NaN,Q1860,2017-06-16,m/otherlife,NaN,Q42531215
12,NaN,"[Q41548, Q104514, Q172261, Q431038]",Q219,[Q15439821],Bullet Head,NaN,"[Q959790, Q182015]",tt6204340,Bullet Head,NaN,NaN,movie/bullet-head,Q1860,2017-01-01,m/bullet_head,NaN,Q42843713
13,NaN,[Q42101],Q30,[Q465139],The Equalizer 2,NaN,"[Q2484376, Q188473]",tt3766354,The Equalizer 2,NaN,NaN,NaN,Q1860,2018-08-30,m/the_equalizer_2,NaN,Q41493467
14,NaN,"[Q229291, Q296616, Q940891, Q2558129, Q19661737]",Q30,NaN,Hereditary (film),NaN,[Q200092],tt7784604,Hereditary,NaN,NaN,movie/hereditary,Q1860,2018-01-21,m/hereditary,NaN,Q47524071
15,NaN,NaN,Q801,[Q30330304],Scaffolding (film),NaN,[Q130232],tt6253214,Scaffolding,NaN,NaN,NaN,Q9288,2017-05-20,m/scaffolding_2017,NaN,Q39073994
16,NaN,"[Q4120019, Q20973952, Q29622423, Q27044068, Q3...",Q30,[Q27044648],Monsters and Men,NaN,[Q130232],tt7689906,Monsters and Men,NaN,NaN,NaN,Q1860,2018-01-01,m/monsters_and_men,NaN,Q47461687
17,NaN,NaN,Q30,[Q47493288],Heroin(e),NaN,[Q93204],tt7389366,Heroin(e),NaN,NaN,NaN,Q1860,2017-01-01,m/heroin,NaN,Q47472042
18,NaN,NaN,Q183,[Q8670824],Monster Family,NaN,"[Q28968258, Q224700]",tt6572702,Monster Family,NaN,NaN,movie/monster-family,Q1860,2017-08-24,m/happy_family_2017,NaN,Q38888554
19,NaN,"[Q254274, Q12225006, Q12249859, Q4165417, Q309...",Q79,[Q312611],The Choice (1970 film),NaN,[Q130232],tt0065879,The Choice,NaN,NaN,NaN,Q13955,1970-01-01,m/alikhtiyar_the_choice,NaN,Q38905900
20,NaN,"[Q16989565, Q16991279]",Q33,[Q11896737],Euthanizer,NaN,"[Q157443, Q53094]",tt6505968,Euthanizer,NaN,NaN,movie/euthanizer,Q1412,2017-09-07,m/euthanizer,NaN,Q39049013
21,NaN,[Q186744],Q30,[Q4954299],Goth (2003 film),NaN,[Q2484376],tt0366530,Goth,NaN,NaN,NaN,Q1860,2003-01-01,m/goth,NaN,Q39071331
22,NaN,NaN,Q30,[Q420041],Outside In (film),NaN,[Q130232],tt7260048,Outside In,NaN,NaN,NaN,Q1860,2017-09-08,m/outside_in_2017,NaN,Q39073873
23,NaN,NaN,Q30,NaN,The Toys That Made Us,NaN,[Q4164344],tt7053920,The Toys That Made Us,NaN,NaN,NaN,Q1860,NaN,tv/the_toys_that_made_us,NaN,Q46965329
24,NaN,"[Q170572, Q192165]",Q145,NaN,Andron (film),NaN,[Q471839],tt4073890,Andron,NaN,NaN,NaN,Q1860,2015-11-08,m/andron,NaN,Q47088341
25,NaN,NaN,Q30,NaN,A Gray State,NaN,[Q93204],tt6794380,A Gray State,NaN,NaN,movie/a-gray-state,NaN,2017-04-01,m/a_gray_state,NaN,Q46997522
26,NaN,NaN,Q30,[Q6270284],Cuba and the Cameraman,NaN,[Q93204],tt7320560,Cuba and the Cameraman,NaN,NaN,movie/cuba-and-the-cameraman,NaN,2017-01-01,m/cuba_and_the_cameraman,NaN,Q47349198
27,NaN,[Q204005],Q408,NaN,Rip Tide (film),NaN,[Q1361932],tt6262764,Rip Tide,NaN,NaN,NaN,Q1860,2017-01-01,m/rip_tide_2017,NaN,Q47445594
28,Q1128242,"[Q228717, Q484615, Q933129]",Q30,[Q3177627],"Juliet, Naked (film)",NaN,[Q859369],tt5607096,"Juliet, Naked",NaN,NaN,NaN,Q1860,2018-01-01,m/juliet_naked,NaN,Q47461719
29,NaN,[Q3195081],Q30,[Q933052],Dangerous Intentions,NaN,[Q130232],tt0112791,Dangerous Intentions,NaN,NaN,NaN,Q1860,1995-01-01,m/dangerous_intentions,NaN,Q47438673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40400,NaN,NaN,Q30,[Q20676250],The Lego Batman Movie,NaN,"[Q157443, Q202866, Q1535153]",tt4116284,The LEGO Batman Movie,NaN,NaN,movie/the-lego-batman-movie,Q1860,2017-02-09,m/the_lego_batman_movie,Q2111133,Q23013169
40401,NaN,NaN,NaN,[Q704027],Kill Time (film),NaN,[Q959790],tt5541542,Kill Time,NaN,NaN,NaN,NaN,2016-02-14,m/kill_time,NaN,Q23013681
40402,NaN,"[Q13426679, Q25144, Q13217306, Q362616, Q31310...",Q145,[Q522057],Baby Driver,NaN,"[Q1788980, Q157443, Q319221]",tt3890160,Baby Driver,NaN,NaN,movie/baby-driver,Q1860,2017-06-30,m/baby_driver,NaN,Q23016644
40403,NaN,"[Q228766, Q202304, Q59215, Q254947, Q1138674, ...",Q30,[Q21872603],The Discovery (film),NaN,"[Q471839, Q1054574]",tt5155780,The Discovery,NaN,NaN,movie/the-discovery,Q1860,2017-01-01,m/the_discovery_2016,NaN,Q23035769
40404,NaN,"[Q38554, Q3293174, Q3021819]",Q142,[Q19628629],La Dormeuse Duval,NaN,[Q157443],tt5279722,The sleeper by the river,NaN,NaN,NaN,Q150,2017-02-08,m/la_dormeuse_duval,NaN,Q23047125
40405,NaN,NaN,Q16,[Q28233390],Corbo (film),NaN,[Q130232],tt3924798,Corbo,NaN,NaN,NaN,Q150,2014-09-04,m/corbo,NaN,Q23058503
40406,NaN,"[Q3621855, Q5673824, Q16298722, Q2889975, Q250...",Q29,[Q3621855],"Kiki, Love to Love",NaN,[Q860626],tt4922692,"Kiki, el amor se hace",NaN,NaN,NaN,Q1321,2016-01-01,m/kiki_love_to_love_2016,NaN,Q23301831
40407,NaN,NaN,Q30,NaN,Brother Outsider,NaN,[Q20442589],tt0337902,Brother Outsider,NaN,NaN,NaN,NaN,2003-01-01,m/brother_outsider_the_life_of_bayard_rustin,NaN,Q23305740
40408,NaN,[Q63187],Q183,[Q1573078],Fog in August,NaN,[Q130232],tt4250566,Fog in August,NaN,NaN,NaN,Q188,2016-09-29,m/nebel_im_august,NaN,Q23564932
40409,NaN,"[Q719330, Q2680, Q40228, Q115932]",Q30,[Q6794687],Precious Cargo (film),NaN,"[Q959790, Q130232]",tt4651410,Precious Cargo,NaN,NaN,NaN,Q33673,2016-04-22,m/precious_cargo_2016,NaN,Q23647134
40410,NaN,[Q13560265],Q30,NaN,Teenage Cocktail,NaN,"[Q130232, Q20442589]",tt1774591,Teenage Cocktail,NaN,NaN,NaN,Q1860,2016-03-12,m/teenage_cocktail,NaN,Q23647155
40411,NaN,NaN,Q16,[Q24671778],When Elephants Were Young,NaN,"[Q93204, Q319221, Q130232, Q1361932]",tt2101347,When Elephants Were Young,NaN,NaN,NaN,Q1860,2015-12-05,m/when_elephants_were_young,NaN,Q23647188
40412,Q534153,"[Q42833024, Q139638, Q312712, Q16202598, Q5591...",Q30,[Q16775487],Shazam! (film),[Q172],"[Q188473, Q1535153, Q157394]",tt0448115,Shazam!,NaN,NaN,NaN,Q1860,2019-04-05,m/shazam,Q18281265,Q23685878
40413,NaN,"[Q140181, Q552026, Q464744, Q3368538, Q233786,...",Q30,NaN,Pandemic (film),NaN,[Q188473],tt3774802,Pandemic,NaN,NaN,movie/pandemic,Q1860,2016-01-01,m/771436221,NaN,Q23707696
40414,NaN,"[Q23711375, Q658160, Q17350573, Q3479511]",Q31,[Q23711374],Death by Death,NaN,"[Q859369, Q157443]",tt3407236,Death by death,NaN,NaN,NaN,Q150,2016-01-01,m/death_by_death,NaN,Q23711369
40415,NaN,NaN,Q30,NaN,Forbidden Sins,NaN,[Q2439025],tt0171326,Forbidden Sins,NaN,NaN,NaN,Q1860,NaN,m/forbidden_sins,NaN,Q23755390
40416,NaN,"[Q32522, Q1148822, Q284636, Q236475, Q723057, ...",Q30,"[Q22323567, Q8003113]",Office Christmas Party,NaN,"[Q157443, Q28026639]",tt1711525,Office Christmas Party,NaN,NaN,movie/office-christmas-party,Q1860,2016-12-08,m/office_christmas_party,NaN,Q23755403
40417,NaN,NaN,Q30,[Q7356958],The Happy Sad,NaN,[Q20442589],tt2049559,The Happy Sad,NaN,NaN,movie/the-happy-sad,Q1860,NaN,m/the_happy_sad_2013,NaN,Q23755410
40418,NaN,"[Q132952, Q47100, Q168724, Q42930, Q76877, Q10...",Q30,[Q459349],The Meyerowitz Stories,NaN,[Q859369],tt5536736,The Meyerowitz Stories,NaN,NaN,movie/the-meyerowitz-stories,Q1860,2017-05-01,m/the_meyerowitz_stories,NaN,Q23755497
40419,NaN,NaN,Q145,"[Q25529450, Q25529490]",Bolshoi Babylon,NaN,[Q93204],tt3505682,Bolshoi Babylon,NaN,NaN,movie/bolshoi-babylon,Q1860,2015-01-01,m/bolshoi_babylon,NaN,Q23755515
40420,NaN,NaN,Q145,NaN,My Beautiful Broken Brain,NaN,[Q93204],tt3815136,My Beautiful Broken Brain,NaN,NaN,NaN,Q1860,2014-01-01,m/my_beautiful_broken_brain,NaN,Q23755616
40421,Q7939693,[Q3028270],Q32,[Q337283],Voices from Chernobyl (film),NaN,"[Q93204, Q17013749, Q1257444]",tt3969688,Voices from Chernobyl,NaN,NaN,NaN,Q150,2016-01-01,m/voices_from_chernobyl,NaN,Q23793868
40422,NaN,"[Q95043, Q128828, Q235503, Q2392907, Q236918, ...",Q30,[Q26904302],The Good Neighbor (film),NaN,[Q9503],tt2262315,The Waiting,NaN,NaN,movie/the-good-neighbor,Q1860,2016-01-01,m/the_waiting_2016,NaN,Q23797161
40423,NaN,"[Q12735604, Q15915101]",Q218,[Q1140264],Sieranevada,NaN,[Q130232],tt4466490,Sieranevada,NaN,NaN,movie/sieranevada,Q7913,2016-01-01,m/sieranevada,NaN,Q23823612
40424,NaN,"[Q1300467, Q70003, Q1929867, Q15434360, Q11956...",Q183,[Q91508],Toni Erdmann,NaN,"[Q130232, Q157443]",tt4048272,Toni Erdmann,NaN,NaN,movie/toni-erdmann,Q188,2016-05-14,m/toni_erdmann,NaN,Q23838395
40425,NaN,"[Q5475290, Q3742898]",Q33,[Q18632044],The Happiest Day in the Life of Olli Mäki,NaN,[Q130232],tt4771932,The Happiest Day in the Life of Olli Mäki,NaN,NaN,movie/the-happiest-day-in-the-life-of-olli-maki,Q1412,2016-05-19,m/the_happiest_day_in_the_life_of_olli_maki_2016,NaN,Q23838435
40426,NaN,NaN,Q30,[Q16223670],The Pistol Shrimps,[Q65],[Q93204],tt5563100,The Pistol Shrimps,NaN,NaN,NaN,Q1860,2016-01-01,m/pistol_shrimps,NaN,Q23838477
40427,NaN,NaN,NaN,"[Q24662017, Q24662021]",The Banksy Job,NaN,[Q93204],tt4406572,The Banksy Job,NaN,NaN,NaN,NaN,2016-01-01,m/the_banksy_job_2016,NaN,Q23848755
40428,NaN,NaN,Q30,[Q1361201],In Jackson Heights,NaN,[Q93204],tt4936064,In Jackson Heights,NaN,NaN,movie/in-jackson-heights,Q1860,2015-09-04,m/in_jackson_heights,NaN,Q23899905
40429,NaN,[Q315723],Q30,[Q518995],The McMasters,NaN,[Q172980],tt0064649,The McMasters,NaN,NaN,NaN,Q1860,1970-01-01,m/the_mcmasters,NaN,Q23899915